export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const SET_USER_DATA = 'SET_USER_DATA';
export const PUT_STUDENTS_LIST = 'PUT_STUDENTS_LIST';
export const SET_IS_SIGNUP = 'SET_IS_SIGNUP';
